// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swf/storage/v1/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChapterRecord struct {
	state                    protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Ordinal       int64                   `protobuf:"varint,1,opt,name=ordinal"`
	xxx_hidden_TaskType      *string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType"`
	xxx_hidden_WorkerId      *string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=created_at,json=createdAt"`
	xxx_hidden_StartedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=started_at,json=startedAt"`
	xxx_hidden_FinishedAt    *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt"`
	xxx_hidden_InputHash     *string                 `protobuf:"bytes,7,opt,name=input_hash,json=inputHash"`
	xxx_hidden_MetadataJson  []byte                  `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson"`
	xxx_hidden_InputJson     []byte                  `protobuf:"bytes,9,opt,name=input_json,json=inputJson"`
	xxx_hidden_Attempt       int32                   `protobuf:"varint,10,opt,name=attempt"`
	xxx_hidden_MaxAttempts   int32                   `protobuf:"varint,11,opt,name=max_attempts,json=maxAttempts"`
	xxx_hidden_NextAttemptAt *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=next_attempt_at,json=nextAttemptAt"`
	xxx_hidden_BackoffMillis int64                   `protobuf:"varint,13,opt,name=backoff_millis,json=backoffMillis"`
	xxx_hidden_Retryable     bool                    `protobuf:"varint,14,opt,name=retryable"`
	xxx_hidden_InputRef      *InputReference         `protobuf:"bytes,15,opt,name=input_ref,json=inputRef"`
	xxx_hidden_RunPolicy     *RunPolicy              `protobuf:"bytes,16,opt,name=run_policy,json=runPolicy"`
	xxx_hidden_Prerequisites *[]*JobPrerequisite     `protobuf:"bytes,17,rep,name=prerequisites"`
	xxx_hidden_Chapter       isChapterRecord_Chapter `protobuf_oneof:"chapter"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ChapterRecord) Reset() {
	*x = ChapterRecord{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterRecord) ProtoMessage() {}

func (x *ChapterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChapterRecord) GetOrdinal() int64 {
	if x != nil {
		return x.xxx_hidden_Ordinal
	}
	return 0
}

func (x *ChapterRecord) GetTaskType() string {
	if x != nil {
		if x.xxx_hidden_TaskType != nil {
			return *x.xxx_hidden_TaskType
		}
		return ""
	}
	return ""
}

func (x *ChapterRecord) GetWorkerId() string {
	if x != nil {
		if x.xxx_hidden_WorkerId != nil {
			return *x.xxx_hidden_WorkerId
		}
		return ""
	}
	return ""
}

func (x *ChapterRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ChapterRecord) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *ChapterRecord) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FinishedAt
	}
	return nil
}

func (x *ChapterRecord) GetInputHash() string {
	if x != nil {
		if x.xxx_hidden_InputHash != nil {
			return *x.xxx_hidden_InputHash
		}
		return ""
	}
	return ""
}

func (x *ChapterRecord) GetMetadataJson() []byte {
	if x != nil {
		return x.xxx_hidden_MetadataJson
	}
	return nil
}

func (x *ChapterRecord) GetInputJson() []byte {
	if x != nil {
		return x.xxx_hidden_InputJson
	}
	return nil
}

func (x *ChapterRecord) GetAttempt() int32 {
	if x != nil {
		return x.xxx_hidden_Attempt
	}
	return 0
}

func (x *ChapterRecord) GetMaxAttempts() int32 {
	if x != nil {
		return x.xxx_hidden_MaxAttempts
	}
	return 0
}

func (x *ChapterRecord) GetNextAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_NextAttemptAt
	}
	return nil
}

func (x *ChapterRecord) GetBackoffMillis() int64 {
	if x != nil {
		return x.xxx_hidden_BackoffMillis
	}
	return 0
}

func (x *ChapterRecord) GetRetryable() bool {
	if x != nil {
		return x.xxx_hidden_Retryable
	}
	return false
}

func (x *ChapterRecord) GetInputRef() *InputReference {
	if x != nil {
		return x.xxx_hidden_InputRef
	}
	return nil
}

func (x *ChapterRecord) GetRunPolicy() *RunPolicy {
	if x != nil {
		return x.xxx_hidden_RunPolicy
	}
	return nil
}

func (x *ChapterRecord) GetPrerequisites() []*JobPrerequisite {
	if x != nil {
		if x.xxx_hidden_Prerequisites != nil {
			return *x.xxx_hidden_Prerequisites
		}
	}
	return nil
}

func (x *ChapterRecord) GetJobStart() *JobStartChapter {
	if x != nil {
		if x, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobStart); ok {
			return x.JobStart
		}
	}
	return nil
}

func (x *ChapterRecord) GetJobAttemptOutcome() *JobAttemptOutcomeChapter {
	if x != nil {
		if x, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobAttemptOutcome); ok {
			return x.JobAttemptOutcome
		}
	}
	return nil
}

func (x *ChapterRecord) GetTaskAttemptOutcome() *TaskAttemptOutcomeChapter {
	if x != nil {
		if x, ok := x.xxx_hidden_Chapter.(*chapterRecord_TaskAttemptOutcome); ok {
			return x.TaskAttemptOutcome
		}
	}
	return nil
}

func (x *ChapterRecord) GetRestartExtra() *RestartExtraChapter {
	if x != nil {
		if x, ok := x.xxx_hidden_Chapter.(*chapterRecord_RestartExtra); ok {
			return x.RestartExtra
		}
	}
	return nil
}

func (x *ChapterRecord) SetOrdinal(v int64) {
	x.xxx_hidden_Ordinal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 18)
}

func (x *ChapterRecord) SetTaskType(v string) {
	x.xxx_hidden_TaskType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 18)
}

func (x *ChapterRecord) SetWorkerId(v string) {
	x.xxx_hidden_WorkerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 18)
}

func (x *ChapterRecord) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ChapterRecord) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *ChapterRecord) SetFinishedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_FinishedAt = v
}

func (x *ChapterRecord) SetInputHash(v string) {
	x.xxx_hidden_InputHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 18)
}

func (x *ChapterRecord) SetMetadataJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MetadataJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 18)
}

func (x *ChapterRecord) SetInputJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_InputJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 18)
}

func (x *ChapterRecord) SetAttempt(v int32) {
	x.xxx_hidden_Attempt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 18)
}

func (x *ChapterRecord) SetMaxAttempts(v int32) {
	x.xxx_hidden_MaxAttempts = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 18)
}

func (x *ChapterRecord) SetNextAttemptAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_NextAttemptAt = v
}

func (x *ChapterRecord) SetBackoffMillis(v int64) {
	x.xxx_hidden_BackoffMillis = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 18)
}

func (x *ChapterRecord) SetRetryable(v bool) {
	x.xxx_hidden_Retryable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 18)
}

func (x *ChapterRecord) SetInputRef(v *InputReference) {
	x.xxx_hidden_InputRef = v
}

func (x *ChapterRecord) SetRunPolicy(v *RunPolicy) {
	x.xxx_hidden_RunPolicy = v
}

func (x *ChapterRecord) SetPrerequisites(v []*JobPrerequisite) {
	x.xxx_hidden_Prerequisites = &v
}

func (x *ChapterRecord) SetJobStart(v *JobStartChapter) {
	if v == nil {
		x.xxx_hidden_Chapter = nil
		return
	}
	x.xxx_hidden_Chapter = &chapterRecord_JobStart{v}
}

func (x *ChapterRecord) SetJobAttemptOutcome(v *JobAttemptOutcomeChapter) {
	if v == nil {
		x.xxx_hidden_Chapter = nil
		return
	}
	x.xxx_hidden_Chapter = &chapterRecord_JobAttemptOutcome{v}
}

func (x *ChapterRecord) SetTaskAttemptOutcome(v *TaskAttemptOutcomeChapter) {
	if v == nil {
		x.xxx_hidden_Chapter = nil
		return
	}
	x.xxx_hidden_Chapter = &chapterRecord_TaskAttemptOutcome{v}
}

func (x *ChapterRecord) SetRestartExtra(v *RestartExtraChapter) {
	if v == nil {
		x.xxx_hidden_Chapter = nil
		return
	}
	x.xxx_hidden_Chapter = &chapterRecord_RestartExtra{v}
}

func (x *ChapterRecord) HasOrdinal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChapterRecord) HasTaskType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChapterRecord) HasWorkerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ChapterRecord) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ChapterRecord) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *ChapterRecord) HasFinishedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FinishedAt != nil
}

func (x *ChapterRecord) HasInputHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ChapterRecord) HasMetadataJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ChapterRecord) HasInputJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ChapterRecord) HasAttempt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ChapterRecord) HasMaxAttempts() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ChapterRecord) HasNextAttemptAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextAttemptAt != nil
}

func (x *ChapterRecord) HasBackoffMillis() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ChapterRecord) HasRetryable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *ChapterRecord) HasInputRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_InputRef != nil
}

func (x *ChapterRecord) HasRunPolicy() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RunPolicy != nil
}

func (x *ChapterRecord) HasChapter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Chapter != nil
}

func (x *ChapterRecord) HasJobStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobStart)
	return ok
}

func (x *ChapterRecord) HasJobAttemptOutcome() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobAttemptOutcome)
	return ok
}

func (x *ChapterRecord) HasTaskAttemptOutcome() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Chapter.(*chapterRecord_TaskAttemptOutcome)
	return ok
}

func (x *ChapterRecord) HasRestartExtra() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Chapter.(*chapterRecord_RestartExtra)
	return ok
}

func (x *ChapterRecord) ClearOrdinal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ordinal = 0
}

func (x *ChapterRecord) ClearTaskType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TaskType = nil
}

func (x *ChapterRecord) ClearWorkerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_WorkerId = nil
}

func (x *ChapterRecord) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *ChapterRecord) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *ChapterRecord) ClearFinishedAt() {
	x.xxx_hidden_FinishedAt = nil
}

func (x *ChapterRecord) ClearInputHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_InputHash = nil
}

func (x *ChapterRecord) ClearMetadataJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_MetadataJson = nil
}

func (x *ChapterRecord) ClearInputJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_InputJson = nil
}

func (x *ChapterRecord) ClearAttempt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Attempt = 0
}

func (x *ChapterRecord) ClearMaxAttempts() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_MaxAttempts = 0
}

func (x *ChapterRecord) ClearNextAttemptAt() {
	x.xxx_hidden_NextAttemptAt = nil
}

func (x *ChapterRecord) ClearBackoffMillis() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_BackoffMillis = 0
}

func (x *ChapterRecord) ClearRetryable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Retryable = false
}

func (x *ChapterRecord) ClearInputRef() {
	x.xxx_hidden_InputRef = nil
}

func (x *ChapterRecord) ClearRunPolicy() {
	x.xxx_hidden_RunPolicy = nil
}

func (x *ChapterRecord) ClearChapter() {
	x.xxx_hidden_Chapter = nil
}

func (x *ChapterRecord) ClearJobStart() {
	if _, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobStart); ok {
		x.xxx_hidden_Chapter = nil
	}
}

func (x *ChapterRecord) ClearJobAttemptOutcome() {
	if _, ok := x.xxx_hidden_Chapter.(*chapterRecord_JobAttemptOutcome); ok {
		x.xxx_hidden_Chapter = nil
	}
}

func (x *ChapterRecord) ClearTaskAttemptOutcome() {
	if _, ok := x.xxx_hidden_Chapter.(*chapterRecord_TaskAttemptOutcome); ok {
		x.xxx_hidden_Chapter = nil
	}
}

func (x *ChapterRecord) ClearRestartExtra() {
	if _, ok := x.xxx_hidden_Chapter.(*chapterRecord_RestartExtra); ok {
		x.xxx_hidden_Chapter = nil
	}
}

const ChapterRecord_Chapter_not_set_case case_ChapterRecord_Chapter = 0
const ChapterRecord_JobStart_case case_ChapterRecord_Chapter = 30
const ChapterRecord_JobAttemptOutcome_case case_ChapterRecord_Chapter = 31
const ChapterRecord_TaskAttemptOutcome_case case_ChapterRecord_Chapter = 32
const ChapterRecord_RestartExtra_case case_ChapterRecord_Chapter = 33

func (x *ChapterRecord) WhichChapter() case_ChapterRecord_Chapter {
	if x == nil {
		return ChapterRecord_Chapter_not_set_case
	}
	switch x.xxx_hidden_Chapter.(type) {
	case *chapterRecord_JobStart:
		return ChapterRecord_JobStart_case
	case *chapterRecord_JobAttemptOutcome:
		return ChapterRecord_JobAttemptOutcome_case
	case *chapterRecord_TaskAttemptOutcome:
		return ChapterRecord_TaskAttemptOutcome_case
	case *chapterRecord_RestartExtra:
		return ChapterRecord_RestartExtra_case
	default:
		return ChapterRecord_Chapter_not_set_case
	}
}

type ChapterRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ordinal       *int64
	TaskType      *string
	WorkerId      *string
	CreatedAt     *timestamppb.Timestamp
	StartedAt     *timestamppb.Timestamp
	FinishedAt    *timestamppb.Timestamp
	InputHash     *string
	MetadataJson  []byte
	InputJson     []byte
	Attempt       *int32
	MaxAttempts   *int32
	NextAttemptAt *timestamppb.Timestamp
	BackoffMillis *int64
	Retryable     *bool
	InputRef      *InputReference
	RunPolicy     *RunPolicy
	Prerequisites []*JobPrerequisite
	// Fields of oneof xxx_hidden_Chapter:
	JobStart           *JobStartChapter
	JobAttemptOutcome  *JobAttemptOutcomeChapter
	TaskAttemptOutcome *TaskAttemptOutcomeChapter
	RestartExtra       *RestartExtraChapter
	// -- end of xxx_hidden_Chapter
}

func (b0 ChapterRecord_builder) Build() *ChapterRecord {
	m0 := &ChapterRecord{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ordinal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 18)
		x.xxx_hidden_Ordinal = *b.Ordinal
	}
	if b.TaskType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 18)
		x.xxx_hidden_TaskType = b.TaskType
	}
	if b.WorkerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 18)
		x.xxx_hidden_WorkerId = b.WorkerId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_FinishedAt = b.FinishedAt
	if b.InputHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 18)
		x.xxx_hidden_InputHash = b.InputHash
	}
	if b.MetadataJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 18)
		x.xxx_hidden_MetadataJson = b.MetadataJson
	}
	if b.InputJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 18)
		x.xxx_hidden_InputJson = b.InputJson
	}
	if b.Attempt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 18)
		x.xxx_hidden_Attempt = *b.Attempt
	}
	if b.MaxAttempts != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 18)
		x.xxx_hidden_MaxAttempts = *b.MaxAttempts
	}
	x.xxx_hidden_NextAttemptAt = b.NextAttemptAt
	if b.BackoffMillis != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 18)
		x.xxx_hidden_BackoffMillis = *b.BackoffMillis
	}
	if b.Retryable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 18)
		x.xxx_hidden_Retryable = *b.Retryable
	}
	x.xxx_hidden_InputRef = b.InputRef
	x.xxx_hidden_RunPolicy = b.RunPolicy
	x.xxx_hidden_Prerequisites = &b.Prerequisites
	if b.JobStart != nil {
		x.xxx_hidden_Chapter = &chapterRecord_JobStart{b.JobStart}
	}
	if b.JobAttemptOutcome != nil {
		x.xxx_hidden_Chapter = &chapterRecord_JobAttemptOutcome{b.JobAttemptOutcome}
	}
	if b.TaskAttemptOutcome != nil {
		x.xxx_hidden_Chapter = &chapterRecord_TaskAttemptOutcome{b.TaskAttemptOutcome}
	}
	if b.RestartExtra != nil {
		x.xxx_hidden_Chapter = &chapterRecord_RestartExtra{b.RestartExtra}
	}
	return m0
}

type case_ChapterRecord_Chapter protoreflect.FieldNumber

func (x case_ChapterRecord_Chapter) String() string {
	md := file_swf_storage_v1_storage_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isChapterRecord_Chapter interface {
	isChapterRecord_Chapter()
}

type chapterRecord_JobStart struct {
	JobStart *JobStartChapter `protobuf:"bytes,30,opt,name=job_start,json=jobStart,oneof"`
}

type chapterRecord_JobAttemptOutcome struct {
	JobAttemptOutcome *JobAttemptOutcomeChapter `protobuf:"bytes,31,opt,name=job_attempt_outcome,json=jobAttemptOutcome,oneof"`
}

type chapterRecord_TaskAttemptOutcome struct {
	TaskAttemptOutcome *TaskAttemptOutcomeChapter `protobuf:"bytes,32,opt,name=task_attempt_outcome,json=taskAttemptOutcome,oneof"`
}

type chapterRecord_RestartExtra struct {
	RestartExtra *RestartExtraChapter `protobuf:"bytes,33,opt,name=restart_extra,json=restartExtra,oneof"`
}

func (*chapterRecord_JobStart) isChapterRecord_Chapter() {}

func (*chapterRecord_JobAttemptOutcome) isChapterRecord_Chapter() {}

func (*chapterRecord_TaskAttemptOutcome) isChapterRecord_Chapter() {}

func (*chapterRecord_RestartExtra) isChapterRecord_Chapter() {}

type JobStartChapter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PayloadJson []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JobStartChapter) Reset() {
	*x = JobStartChapter{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStartChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartChapter) ProtoMessage() {}

func (x *JobStartChapter) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobStartChapter) GetPayloadJson() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadJson
	}
	return nil
}

func (x *JobStartChapter) SetPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *JobStartChapter) HasPayloadJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobStartChapter) ClearPayloadJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PayloadJson = nil
}

type JobStartChapter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PayloadJson []byte
}

func (b0 JobStartChapter_builder) Build() *JobStartChapter {
	m0 := &JobStartChapter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PayloadJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_PayloadJson = b.PayloadJson
	}
	return m0
}

type JobAttemptOutcomeChapter struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Outcome *TaskOutcome           `protobuf:"bytes,1,opt,name=outcome"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobAttemptOutcomeChapter) Reset() {
	*x = JobAttemptOutcomeChapter{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAttemptOutcomeChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAttemptOutcomeChapter) ProtoMessage() {}

func (x *JobAttemptOutcomeChapter) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobAttemptOutcomeChapter) GetOutcome() *TaskOutcome {
	if x != nil {
		return x.xxx_hidden_Outcome
	}
	return nil
}

func (x *JobAttemptOutcomeChapter) SetOutcome(v *TaskOutcome) {
	x.xxx_hidden_Outcome = v
}

func (x *JobAttemptOutcomeChapter) HasOutcome() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Outcome != nil
}

func (x *JobAttemptOutcomeChapter) ClearOutcome() {
	x.xxx_hidden_Outcome = nil
}

type JobAttemptOutcomeChapter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Outcome *TaskOutcome
}

func (b0 JobAttemptOutcomeChapter_builder) Build() *JobAttemptOutcomeChapter {
	m0 := &JobAttemptOutcomeChapter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Outcome = b.Outcome
	return m0
}

type TaskAttemptOutcomeChapter struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Outcome *TaskOutcome           `protobuf:"bytes,1,opt,name=outcome"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskAttemptOutcomeChapter) Reset() {
	*x = TaskAttemptOutcomeChapter{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAttemptOutcomeChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAttemptOutcomeChapter) ProtoMessage() {}

func (x *TaskAttemptOutcomeChapter) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskAttemptOutcomeChapter) GetOutcome() *TaskOutcome {
	if x != nil {
		return x.xxx_hidden_Outcome
	}
	return nil
}

func (x *TaskAttemptOutcomeChapter) SetOutcome(v *TaskOutcome) {
	x.xxx_hidden_Outcome = v
}

func (x *TaskAttemptOutcomeChapter) HasOutcome() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Outcome != nil
}

func (x *TaskAttemptOutcomeChapter) ClearOutcome() {
	x.xxx_hidden_Outcome = nil
}

type TaskAttemptOutcomeChapter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Outcome *TaskOutcome
}

func (b0 TaskAttemptOutcomeChapter_builder) Build() *TaskAttemptOutcomeChapter {
	m0 := &TaskAttemptOutcomeChapter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Outcome = b.Outcome
	return m0
}

type RestartExtraChapter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PayloadJson []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RestartExtraChapter) Reset() {
	*x = RestartExtraChapter{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartExtraChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartExtraChapter) ProtoMessage() {}

func (x *RestartExtraChapter) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartExtraChapter) GetPayloadJson() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadJson
	}
	return nil
}

func (x *RestartExtraChapter) SetPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RestartExtraChapter) HasPayloadJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RestartExtraChapter) ClearPayloadJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PayloadJson = nil
}

type RestartExtraChapter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PayloadJson []byte
}

func (b0 RestartExtraChapter_builder) Build() *RestartExtraChapter {
	m0 := &RestartExtraChapter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PayloadJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_PayloadJson = b.PayloadJson
	}
	return m0
}

type TaskOutcome struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result isTaskOutcome_Result   `protobuf_oneof:"result"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskOutcome) Reset() {
	*x = TaskOutcome{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutcome) ProtoMessage() {}

func (x *TaskOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskOutcome) GetAppPayloadJson() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*taskOutcome_AppPayloadJson); ok {
			return x.AppPayloadJson
		}
	}
	return nil
}

func (x *TaskOutcome) GetAppErrorPayloadJson() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*taskOutcome_AppErrorPayloadJson); ok {
			return x.AppErrorPayloadJson
		}
	}
	return nil
}

func (x *TaskOutcome) GetSystemErrorPayloadJson() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*taskOutcome_SystemErrorPayloadJson); ok {
			return x.SystemErrorPayloadJson
		}
	}
	return nil
}

func (x *TaskOutcome) GetTimeoutPayloadJson() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*taskOutcome_TimeoutPayloadJson); ok {
			return x.TimeoutPayloadJson
		}
	}
	return nil
}

func (x *TaskOutcome) SetAppPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Result = &taskOutcome_AppPayloadJson{v}
}

func (x *TaskOutcome) SetAppErrorPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Result = &taskOutcome_AppErrorPayloadJson{v}
}

func (x *TaskOutcome) SetSystemErrorPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Result = &taskOutcome_SystemErrorPayloadJson{v}
}

func (x *TaskOutcome) SetTimeoutPayloadJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Result = &taskOutcome_TimeoutPayloadJson{v}
}

func (x *TaskOutcome) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *TaskOutcome) HasAppPayloadJson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*taskOutcome_AppPayloadJson)
	return ok
}

func (x *TaskOutcome) HasAppErrorPayloadJson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*taskOutcome_AppErrorPayloadJson)
	return ok
}

func (x *TaskOutcome) HasSystemErrorPayloadJson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*taskOutcome_SystemErrorPayloadJson)
	return ok
}

func (x *TaskOutcome) HasTimeoutPayloadJson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*taskOutcome_TimeoutPayloadJson)
	return ok
}

func (x *TaskOutcome) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *TaskOutcome) ClearAppPayloadJson() {
	if _, ok := x.xxx_hidden_Result.(*taskOutcome_AppPayloadJson); ok {
		x.xxx_hidden_Result = nil
	}
}

func (x *TaskOutcome) ClearAppErrorPayloadJson() {
	if _, ok := x.xxx_hidden_Result.(*taskOutcome_AppErrorPayloadJson); ok {
		x.xxx_hidden_Result = nil
	}
}

func (x *TaskOutcome) ClearSystemErrorPayloadJson() {
	if _, ok := x.xxx_hidden_Result.(*taskOutcome_SystemErrorPayloadJson); ok {
		x.xxx_hidden_Result = nil
	}
}

func (x *TaskOutcome) ClearTimeoutPayloadJson() {
	if _, ok := x.xxx_hidden_Result.(*taskOutcome_TimeoutPayloadJson); ok {
		x.xxx_hidden_Result = nil
	}
}

const TaskOutcome_Result_not_set_case case_TaskOutcome_Result = 0
const TaskOutcome_AppPayloadJson_case case_TaskOutcome_Result = 1
const TaskOutcome_AppErrorPayloadJson_case case_TaskOutcome_Result = 2
const TaskOutcome_SystemErrorPayloadJson_case case_TaskOutcome_Result = 3
const TaskOutcome_TimeoutPayloadJson_case case_TaskOutcome_Result = 4

func (x *TaskOutcome) WhichResult() case_TaskOutcome_Result {
	if x == nil {
		return TaskOutcome_Result_not_set_case
	}
	switch x.xxx_hidden_Result.(type) {
	case *taskOutcome_AppPayloadJson:
		return TaskOutcome_AppPayloadJson_case
	case *taskOutcome_AppErrorPayloadJson:
		return TaskOutcome_AppErrorPayloadJson_case
	case *taskOutcome_SystemErrorPayloadJson:
		return TaskOutcome_SystemErrorPayloadJson_case
	case *taskOutcome_TimeoutPayloadJson:
		return TaskOutcome_TimeoutPayloadJson_case
	default:
		return TaskOutcome_Result_not_set_case
	}
}

type TaskOutcome_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Result:
	AppPayloadJson         []byte
	AppErrorPayloadJson    []byte
	SystemErrorPayloadJson []byte
	TimeoutPayloadJson     []byte
	// -- end of xxx_hidden_Result
}

func (b0 TaskOutcome_builder) Build() *TaskOutcome {
	m0 := &TaskOutcome{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AppPayloadJson != nil {
		x.xxx_hidden_Result = &taskOutcome_AppPayloadJson{b.AppPayloadJson}
	}
	if b.AppErrorPayloadJson != nil {
		x.xxx_hidden_Result = &taskOutcome_AppErrorPayloadJson{b.AppErrorPayloadJson}
	}
	if b.SystemErrorPayloadJson != nil {
		x.xxx_hidden_Result = &taskOutcome_SystemErrorPayloadJson{b.SystemErrorPayloadJson}
	}
	if b.TimeoutPayloadJson != nil {
		x.xxx_hidden_Result = &taskOutcome_TimeoutPayloadJson{b.TimeoutPayloadJson}
	}
	return m0
}

type case_TaskOutcome_Result protoreflect.FieldNumber

func (x case_TaskOutcome_Result) String() string {
	md := file_swf_storage_v1_storage_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTaskOutcome_Result interface {
	isTaskOutcome_Result()
}

type taskOutcome_AppPayloadJson struct {
	AppPayloadJson []byte `protobuf:"bytes,1,opt,name=app_payload_json,json=appPayloadJson,oneof"`
}

type taskOutcome_AppErrorPayloadJson struct {
	AppErrorPayloadJson []byte `protobuf:"bytes,2,opt,name=app_error_payload_json,json=appErrorPayloadJson,oneof"`
}

type taskOutcome_SystemErrorPayloadJson struct {
	SystemErrorPayloadJson []byte `protobuf:"bytes,3,opt,name=system_error_payload_json,json=systemErrorPayloadJson,oneof"`
}

type taskOutcome_TimeoutPayloadJson struct {
	TimeoutPayloadJson []byte `protobuf:"bytes,4,opt,name=timeout_payload_json,json=timeoutPayloadJson,oneof"`
}

func (*taskOutcome_AppPayloadJson) isTaskOutcome_Result() {}

func (*taskOutcome_AppErrorPayloadJson) isTaskOutcome_Result() {}

func (*taskOutcome_SystemErrorPayloadJson) isTaskOutcome_Result() {}

func (*taskOutcome_TimeoutPayloadJson) isTaskOutcome_Result() {}

type InputReference struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ordinal     int64                  `protobuf:"varint,1,opt,name=ordinal"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InputReference) Reset() {
	*x = InputReference{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputReference) ProtoMessage() {}

func (x *InputReference) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InputReference) GetOrdinal() int64 {
	if x != nil {
		return x.xxx_hidden_Ordinal
	}
	return 0
}

func (x *InputReference) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *InputReference) SetOrdinal(v int64) {
	x.xxx_hidden_Ordinal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *InputReference) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *InputReference) HasOrdinal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InputReference) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InputReference) ClearOrdinal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ordinal = 0
}

func (x *InputReference) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Hash = nil
}

type InputReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ordinal *int64
	Hash    *string
}

func (b0 InputReference_builder) Build() *InputReference {
	m0 := &InputReference{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ordinal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Ordinal = *b.Ordinal
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Hash = b.Hash
	}
	return m0
}

type RetryPolicy struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InitialInterval        *durationpb.Duration   `protobuf:"bytes,1,opt,name=initial_interval,json=initialInterval"`
	xxx_hidden_BackoffCoefficient     float64                `protobuf:"fixed64,2,opt,name=backoff_coefficient,json=backoffCoefficient"`
	xxx_hidden_MaximumInterval        *durationpb.Duration   `protobuf:"bytes,3,opt,name=maximum_interval,json=maximumInterval"`
	xxx_hidden_MaximumAttempts        int32                  `protobuf:"varint,4,opt,name=maximum_attempts,json=maximumAttempts"`
	xxx_hidden_NonRetryableErrorTypes []string               `protobuf:"bytes,5,rep,name=non_retryable_error_types,json=nonRetryableErrorTypes"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RetryPolicy) GetInitialInterval() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_InitialInterval
	}
	return nil
}

func (x *RetryPolicy) GetBackoffCoefficient() float64 {
	if x != nil {
		return x.xxx_hidden_BackoffCoefficient
	}
	return 0
}

func (x *RetryPolicy) GetMaximumInterval() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_MaximumInterval
	}
	return nil
}

func (x *RetryPolicy) GetMaximumAttempts() int32 {
	if x != nil {
		return x.xxx_hidden_MaximumAttempts
	}
	return 0
}

func (x *RetryPolicy) GetNonRetryableErrorTypes() []string {
	if x != nil {
		return x.xxx_hidden_NonRetryableErrorTypes
	}
	return nil
}

func (x *RetryPolicy) SetInitialInterval(v *durationpb.Duration) {
	x.xxx_hidden_InitialInterval = v
}

func (x *RetryPolicy) SetBackoffCoefficient(v float64) {
	x.xxx_hidden_BackoffCoefficient = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RetryPolicy) SetMaximumInterval(v *durationpb.Duration) {
	x.xxx_hidden_MaximumInterval = v
}

func (x *RetryPolicy) SetMaximumAttempts(v int32) {
	x.xxx_hidden_MaximumAttempts = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *RetryPolicy) SetNonRetryableErrorTypes(v []string) {
	x.xxx_hidden_NonRetryableErrorTypes = v
}

func (x *RetryPolicy) HasInitialInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_InitialInterval != nil
}

func (x *RetryPolicy) HasBackoffCoefficient() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RetryPolicy) HasMaximumInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MaximumInterval != nil
}

func (x *RetryPolicy) HasMaximumAttempts() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RetryPolicy) ClearInitialInterval() {
	x.xxx_hidden_InitialInterval = nil
}

func (x *RetryPolicy) ClearBackoffCoefficient() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BackoffCoefficient = 0
}

func (x *RetryPolicy) ClearMaximumInterval() {
	x.xxx_hidden_MaximumInterval = nil
}

func (x *RetryPolicy) ClearMaximumAttempts() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MaximumAttempts = 0
}

type RetryPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InitialInterval        *durationpb.Duration
	BackoffCoefficient     *float64
	MaximumInterval        *durationpb.Duration
	MaximumAttempts        *int32
	NonRetryableErrorTypes []string
}

func (b0 RetryPolicy_builder) Build() *RetryPolicy {
	m0 := &RetryPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InitialInterval = b.InitialInterval
	if b.BackoffCoefficient != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_BackoffCoefficient = *b.BackoffCoefficient
	}
	x.xxx_hidden_MaximumInterval = b.MaximumInterval
	if b.MaximumAttempts != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_MaximumAttempts = *b.MaximumAttempts
	}
	x.xxx_hidden_NonRetryableErrorTypes = b.NonRetryableErrorTypes
	return m0
}

type RunPolicy struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Retry             *RetryPolicy           `protobuf:"bytes,1,opt,name=retry"`
	xxx_hidden_InvocationTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=invocation_timeout,json=invocationTimeout"`
	xxx_hidden_TotalTimeout      *durationpb.Duration   `protobuf:"bytes,3,opt,name=total_timeout,json=totalTimeout"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RunPolicy) Reset() {
	*x = RunPolicy{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPolicy) ProtoMessage() {}

func (x *RunPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RunPolicy) GetRetry() *RetryPolicy {
	if x != nil {
		return x.xxx_hidden_Retry
	}
	return nil
}

func (x *RunPolicy) GetInvocationTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_InvocationTimeout
	}
	return nil
}

func (x *RunPolicy) GetTotalTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_TotalTimeout
	}
	return nil
}

func (x *RunPolicy) SetRetry(v *RetryPolicy) {
	x.xxx_hidden_Retry = v
}

func (x *RunPolicy) SetInvocationTimeout(v *durationpb.Duration) {
	x.xxx_hidden_InvocationTimeout = v
}

func (x *RunPolicy) SetTotalTimeout(v *durationpb.Duration) {
	x.xxx_hidden_TotalTimeout = v
}

func (x *RunPolicy) HasRetry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Retry != nil
}

func (x *RunPolicy) HasInvocationTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_InvocationTimeout != nil
}

func (x *RunPolicy) HasTotalTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TotalTimeout != nil
}

func (x *RunPolicy) ClearRetry() {
	x.xxx_hidden_Retry = nil
}

func (x *RunPolicy) ClearInvocationTimeout() {
	x.xxx_hidden_InvocationTimeout = nil
}

func (x *RunPolicy) ClearTotalTimeout() {
	x.xxx_hidden_TotalTimeout = nil
}

type RunPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Retry             *RetryPolicy
	InvocationTimeout *durationpb.Duration
	TotalTimeout      *durationpb.Duration
}

func (b0 RunPolicy_builder) Build() *RunPolicy {
	m0 := &RunPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Retry = b.Retry
	x.xxx_hidden_InvocationTimeout = b.InvocationTimeout
	x.xxx_hidden_TotalTimeout = b.TotalTimeout
	return m0
}

type JobPrerequisite struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId       *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId"`
	xxx_hidden_Condition   *string                `protobuf:"bytes,2,opt,name=condition"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JobPrerequisite) Reset() {
	*x = JobPrerequisite{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPrerequisite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPrerequisite) ProtoMessage() {}

func (x *JobPrerequisite) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobPrerequisite) GetJobId() string {
	if x != nil {
		if x.xxx_hidden_JobId != nil {
			return *x.xxx_hidden_JobId
		}
		return ""
	}
	return ""
}

func (x *JobPrerequisite) GetCondition() string {
	if x != nil {
		if x.xxx_hidden_Condition != nil {
			return *x.xxx_hidden_Condition
		}
		return ""
	}
	return ""
}

func (x *JobPrerequisite) SetJobId(v string) {
	x.xxx_hidden_JobId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *JobPrerequisite) SetCondition(v string) {
	x.xxx_hidden_Condition = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *JobPrerequisite) HasJobId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobPrerequisite) HasCondition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobPrerequisite) ClearJobId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_JobId = nil
}

func (x *JobPrerequisite) ClearCondition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Condition = nil
}

type JobPrerequisite_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	JobId     *string
	Condition *string
}

func (b0 JobPrerequisite_builder) Build() *JobPrerequisite {
	m0 := &JobPrerequisite{}
	b, x := &b0, m0
	_, _ = b, x
	if b.JobId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_JobId = b.JobId
	}
	if b.Condition != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Condition = b.Condition
	}
	return m0
}

type SchedulerPayload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunPolicy *RunPolicy             `protobuf:"bytes,1,opt,name=run_policy,json=runPolicy"`
	xxx_hidden_TaskWait  *TaskWait              `protobuf:"bytes,2,opt,name=task_wait,json=taskWait"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SchedulerPayload) Reset() {
	*x = SchedulerPayload{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerPayload) ProtoMessage() {}

func (x *SchedulerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SchedulerPayload) GetRunPolicy() *RunPolicy {
	if x != nil {
		return x.xxx_hidden_RunPolicy
	}
	return nil
}

func (x *SchedulerPayload) GetTaskWait() *TaskWait {
	if x != nil {
		return x.xxx_hidden_TaskWait
	}
	return nil
}

func (x *SchedulerPayload) SetRunPolicy(v *RunPolicy) {
	x.xxx_hidden_RunPolicy = v
}

func (x *SchedulerPayload) SetTaskWait(v *TaskWait) {
	x.xxx_hidden_TaskWait = v
}

func (x *SchedulerPayload) HasRunPolicy() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RunPolicy != nil
}

func (x *SchedulerPayload) HasTaskWait() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TaskWait != nil
}

func (x *SchedulerPayload) ClearRunPolicy() {
	x.xxx_hidden_RunPolicy = nil
}

func (x *SchedulerPayload) ClearTaskWait() {
	x.xxx_hidden_TaskWait = nil
}

type SchedulerPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RunPolicy *RunPolicy
	TaskWait  *TaskWait
}

func (b0 SchedulerPayload_builder) Build() *SchedulerPayload {
	m0 := &SchedulerPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RunPolicy = b.RunPolicy
	x.xxx_hidden_TaskWait = b.TaskWait
	return m0
}

type TaskWait struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InputStep   int64                  `protobuf:"varint,1,opt,name=input_step,json=inputStep"`
	xxx_hidden_OutputStep  int64                  `protobuf:"varint,2,opt,name=output_step,json=outputStep"`
	xxx_hidden_Next        *string                `protobuf:"bytes,3,opt,name=next"`
	xxx_hidden_InputHash   *string                `protobuf:"bytes,4,opt,name=input_hash,json=inputHash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskWait) Reset() {
	*x = TaskWait{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskWait) ProtoMessage() {}

func (x *TaskWait) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskWait) GetInputStep() int64 {
	if x != nil {
		return x.xxx_hidden_InputStep
	}
	return 0
}

func (x *TaskWait) GetOutputStep() int64 {
	if x != nil {
		return x.xxx_hidden_OutputStep
	}
	return 0
}

func (x *TaskWait) GetNext() string {
	if x != nil {
		if x.xxx_hidden_Next != nil {
			return *x.xxx_hidden_Next
		}
		return ""
	}
	return ""
}

func (x *TaskWait) GetInputHash() string {
	if x != nil {
		if x.xxx_hidden_InputHash != nil {
			return *x.xxx_hidden_InputHash
		}
		return ""
	}
	return ""
}

func (x *TaskWait) SetInputStep(v int64) {
	x.xxx_hidden_InputStep = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *TaskWait) SetOutputStep(v int64) {
	x.xxx_hidden_OutputStep = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TaskWait) SetNext(v string) {
	x.xxx_hidden_Next = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TaskWait) SetInputHash(v string) {
	x.xxx_hidden_InputHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TaskWait) HasInputStep() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TaskWait) HasOutputStep() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TaskWait) HasNext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TaskWait) HasInputHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TaskWait) ClearInputStep() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InputStep = 0
}

func (x *TaskWait) ClearOutputStep() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OutputStep = 0
}

func (x *TaskWait) ClearNext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Next = nil
}

func (x *TaskWait) ClearInputHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_InputHash = nil
}

type TaskWait_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InputStep  *int64
	OutputStep *int64
	Next       *string
	InputHash  *string
}

func (b0 TaskWait_builder) Build() *TaskWait {
	m0 := &TaskWait{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InputStep != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_InputStep = *b.InputStep
	}
	if b.OutputStep != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_OutputStep = *b.OutputStep
	}
	if b.Next != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Next = b.Next
	}
	if b.InputHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_InputHash = b.InputHash
	}
	return m0
}

type WaitForJobs struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobIds []string               `protobuf:"bytes,1,rep,name=job_ids,json=jobIds"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WaitForJobs) Reset() {
	*x = WaitForJobs{}
	mi := &file_swf_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForJobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForJobs) ProtoMessage() {}

func (x *WaitForJobs) ProtoReflect() protoreflect.Message {
	mi := &file_swf_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WaitForJobs) GetJobIds() []string {
	if x != nil {
		return x.xxx_hidden_JobIds
	}
	return nil
}

func (x *WaitForJobs) SetJobIds(v []string) {
	x.xxx_hidden_JobIds = v
}

type WaitForJobs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	JobIds []string
}

func (b0 WaitForJobs_builder) Build() *WaitForJobs {
	m0 := &WaitForJobs{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobIds = b.JobIds
	return m0
}

var File_swf_storage_v1_storage_proto protoreflect.FileDescriptor

const file_swf_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x1cswf/storage/v1/storage.proto\x12\x0eswf.storage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\b\n" +
	"\rChapterRecord\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x03R\aordinal\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1d\n" +
	"\n" +
	"input_hash\x18\a \x01(\tR\tinputHash\x12#\n" +
	"\rmetadata_json\x18\b \x01(\fR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"input_json\x18\t \x01(\fR\tinputJson\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\v \x01(\x05R\vmaxAttempts\x12B\n" +
	"\x0fnext_attempt_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rnextAttemptAt\x12%\n" +
	"\x0ebackoff_millis\x18\r \x01(\x03R\rbackoffMillis\x12\x1c\n" +
	"\tretryable\x18\x0e \x01(\bR\tretryable\x12;\n" +
	"\tinput_ref\x18\x0f \x01(\v2\x1e.swf.storage.v1.InputReferenceR\binputRef\x128\n" +
	"\n" +
	"run_policy\x18\x10 \x01(\v2\x19.swf.storage.v1.RunPolicyR\trunPolicy\x12E\n" +
	"\rprerequisites\x18\x11 \x03(\v2\x1f.swf.storage.v1.JobPrerequisiteR\rprerequisites\x12>\n" +
	"\tjob_start\x18\x1e \x01(\v2\x1f.swf.storage.v1.JobStartChapterH\x00R\bjobStart\x12Z\n" +
	"\x13job_attempt_outcome\x18\x1f \x01(\v2(.swf.storage.v1.JobAttemptOutcomeChapterH\x00R\x11jobAttemptOutcome\x12]\n" +
	"\x14task_attempt_outcome\x18  \x01(\v2).swf.storage.v1.TaskAttemptOutcomeChapterH\x00R\x12taskAttemptOutcome\x12J\n" +
	"\rrestart_extra\x18! \x01(\v2#.swf.storage.v1.RestartExtraChapterH\x00R\frestartExtraB\t\n" +
	"\achapter\"4\n" +
	"\x0fJobStartChapter\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\"Q\n" +
	"\x18JobAttemptOutcomeChapter\x125\n" +
	"\aoutcome\x18\x01 \x01(\v2\x1b.swf.storage.v1.TaskOutcomeR\aoutcome\"R\n" +
	"\x19TaskAttemptOutcomeChapter\x125\n" +
	"\aoutcome\x18\x01 \x01(\v2\x1b.swf.storage.v1.TaskOutcomeR\aoutcome\"8\n" +
	"\x13RestartExtraChapter\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\"\xeb\x01\n" +
	"\vTaskOutcome\x12*\n" +
	"\x10app_payload_json\x18\x01 \x01(\fH\x00R\x0eappPayloadJson\x125\n" +
	"\x16app_error_payload_json\x18\x02 \x01(\fH\x00R\x13appErrorPayloadJson\x12;\n" +
	"\x19system_error_payload_json\x18\x03 \x01(\fH\x00R\x16systemErrorPayloadJson\x122\n" +
	"\x14timeout_payload_json\x18\x04 \x01(\fH\x00R\x12timeoutPayloadJsonB\b\n" +
	"\x06result\">\n" +
	"\x0eInputReference\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x03R\aordinal\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"\xb0\x02\n" +
	"\vRetryPolicy\x12D\n" +
	"\x10initial_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0finitialInterval\x12/\n" +
	"\x13backoff_coefficient\x18\x02 \x01(\x01R\x12backoffCoefficient\x12D\n" +
	"\x10maximum_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fmaximumInterval\x12)\n" +
	"\x10maximum_attempts\x18\x04 \x01(\x05R\x0fmaximumAttempts\x129\n" +
	"\x19non_retryable_error_types\x18\x05 \x03(\tR\x16nonRetryableErrorTypes\"\xc8\x01\n" +
	"\tRunPolicy\x121\n" +
	"\x05retry\x18\x01 \x01(\v2\x1b.swf.storage.v1.RetryPolicyR\x05retry\x12H\n" +
	"\x12invocation_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11invocationTimeout\x12>\n" +
	"\rtotal_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\ftotalTimeout\"F\n" +
	"\x0fJobPrerequisite\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\"\x83\x01\n" +
	"\x10SchedulerPayload\x128\n" +
	"\n" +
	"run_policy\x18\x01 \x01(\v2\x19.swf.storage.v1.RunPolicyR\trunPolicy\x125\n" +
	"\ttask_wait\x18\x02 \x01(\v2\x18.swf.storage.v1.TaskWaitR\btaskWait\"}\n" +
	"\bTaskWait\x12\x1d\n" +
	"\n" +
	"input_step\x18\x01 \x01(\x03R\tinputStep\x12\x1f\n" +
	"\voutput_step\x18\x02 \x01(\x03R\n" +
	"outputStep\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x04 \x01(\tR\tinputHash\"&\n" +
	"\vWaitForJobs\x12\x17\n" +
	"\ajob_ids\x18\x01 \x03(\tR\x06jobIdsBDZBgithub.com/colony-2/swf-go/pkg/swf/internal/storagepb/v1;storagepbb\beditionsp\xe9\a"

var file_swf_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_swf_storage_v1_storage_proto_goTypes = []any{
	(*ChapterRecord)(nil),             // 0: swf.storage.v1.ChapterRecord
	(*JobStartChapter)(nil),           // 1: swf.storage.v1.JobStartChapter
	(*JobAttemptOutcomeChapter)(nil),  // 2: swf.storage.v1.JobAttemptOutcomeChapter
	(*TaskAttemptOutcomeChapter)(nil), // 3: swf.storage.v1.TaskAttemptOutcomeChapter
	(*RestartExtraChapter)(nil),       // 4: swf.storage.v1.RestartExtraChapter
	(*TaskOutcome)(nil),               // 5: swf.storage.v1.TaskOutcome
	(*InputReference)(nil),            // 6: swf.storage.v1.InputReference
	(*RetryPolicy)(nil),               // 7: swf.storage.v1.RetryPolicy
	(*RunPolicy)(nil),                 // 8: swf.storage.v1.RunPolicy
	(*JobPrerequisite)(nil),           // 9: swf.storage.v1.JobPrerequisite
	(*SchedulerPayload)(nil),          // 10: swf.storage.v1.SchedulerPayload
	(*TaskWait)(nil),                  // 11: swf.storage.v1.TaskWait
	(*WaitForJobs)(nil),               // 12: swf.storage.v1.WaitForJobs
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 14: google.protobuf.Duration
}
var file_swf_storage_v1_storage_proto_depIdxs = []int32{
	13, // 0: swf.storage.v1.ChapterRecord.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: swf.storage.v1.ChapterRecord.started_at:type_name -> google.protobuf.Timestamp
	13, // 2: swf.storage.v1.ChapterRecord.finished_at:type_name -> google.protobuf.Timestamp
	13, // 3: swf.storage.v1.ChapterRecord.next_attempt_at:type_name -> google.protobuf.Timestamp
	6,  // 4: swf.storage.v1.ChapterRecord.input_ref:type_name -> swf.storage.v1.InputReference
	8,  // 5: swf.storage.v1.ChapterRecord.run_policy:type_name -> swf.storage.v1.RunPolicy
	9,  // 6: swf.storage.v1.ChapterRecord.prerequisites:type_name -> swf.storage.v1.JobPrerequisite
	1,  // 7: swf.storage.v1.ChapterRecord.job_start:type_name -> swf.storage.v1.JobStartChapter
	2,  // 8: swf.storage.v1.ChapterRecord.job_attempt_outcome:type_name -> swf.storage.v1.JobAttemptOutcomeChapter
	3,  // 9: swf.storage.v1.ChapterRecord.task_attempt_outcome:type_name -> swf.storage.v1.TaskAttemptOutcomeChapter
	4,  // 10: swf.storage.v1.ChapterRecord.restart_extra:type_name -> swf.storage.v1.RestartExtraChapter
	5,  // 11: swf.storage.v1.JobAttemptOutcomeChapter.outcome:type_name -> swf.storage.v1.TaskOutcome
	5,  // 12: swf.storage.v1.TaskAttemptOutcomeChapter.outcome:type_name -> swf.storage.v1.TaskOutcome
	14, // 13: swf.storage.v1.RetryPolicy.initial_interval:type_name -> google.protobuf.Duration
	14, // 14: swf.storage.v1.RetryPolicy.maximum_interval:type_name -> google.protobuf.Duration
	7,  // 15: swf.storage.v1.RunPolicy.retry:type_name -> swf.storage.v1.RetryPolicy
	14, // 16: swf.storage.v1.RunPolicy.invocation_timeout:type_name -> google.protobuf.Duration
	14, // 17: swf.storage.v1.RunPolicy.total_timeout:type_name -> google.protobuf.Duration
	8,  // 18: swf.storage.v1.SchedulerPayload.run_policy:type_name -> swf.storage.v1.RunPolicy
	11, // 19: swf.storage.v1.SchedulerPayload.task_wait:type_name -> swf.storage.v1.TaskWait
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_swf_storage_v1_storage_proto_init() }
func file_swf_storage_v1_storage_proto_init() {
	if File_swf_storage_v1_storage_proto != nil {
		return
	}
	file_swf_storage_v1_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*chapterRecord_JobStart)(nil),
		(*chapterRecord_JobAttemptOutcome)(nil),
		(*chapterRecord_TaskAttemptOutcome)(nil),
		(*chapterRecord_RestartExtra)(nil),
	}
	file_swf_storage_v1_storage_proto_msgTypes[5].OneofWrappers = []any{
		(*taskOutcome_AppPayloadJson)(nil),
		(*taskOutcome_AppErrorPayloadJson)(nil),
		(*taskOutcome_SystemErrorPayloadJson)(nil),
		(*taskOutcome_TimeoutPayloadJson)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swf_storage_v1_storage_proto_rawDesc), len(file_swf_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swf_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_swf_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_swf_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_swf_storage_v1_storage_proto = out.File
	file_swf_storage_v1_storage_proto_goTypes = nil
	file_swf_storage_v1_storage_proto_depIdxs = nil
}
